version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge
